# NumPy - Numerical Python

## Import NumPy

In [2]:
import numpy as np

## Basics

In [8]:
a = np.array([1, 2, 3], dtype="int32")
b = np.array([[4.0, 5.0, 6.0],
              [7.0, 8.0, 9.0]])

In [4]:
print(f"dimension of array a: {a.ndim}")
print(f"dimension of array b: {b.ndim}")

dimension of array a: 1
dimension of array b: 2


In [5]:
print(f"shape of array a: {a.shape}")
print(f"shape of array b: {b.shape}")

shape of array a: (3,)
shape of array b: (2, 3)


In [9]:
print(f"data type of array a: {a.dtype}")
print(f"data type of array b: {b.dtype}")

data type of array a: int32
data type of array b: float64


In [11]:
print(f"Item size of array a: {a.itemsize} bytes")
print(f"Item size of array b: {b.itemsize} bytes")

Item size of array a: 4 bytes
Item size of array b: 8 bytes


In [12]:
print(f"total bytes of array a: {a.nbytes}")
print(f"total bytes of array b: {b.nbytes}")

total bytes of array a: 12
total bytes of array b: 48


## Accessing, Indexing, Slicing

In [13]:
a = np.array([[1, 2, 3, 4, 5, 6, 7],
              [8, 9, 10, 11, 12, 13, 14]])

In [15]:
print(a[1, 5]) # accessing 13

13


In [28]:
a[1, 5] = 15 # modify specific element
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 15 14]]


In [29]:
a[1:] # access row 1

array([[ 8,  9, 10, 11, 12, 15, 14]])

In [33]:
a[:,5] # access column 5

array([ 6, 15])

In [40]:
print(a[0, 1:7:2], a[-2, 1:-1:2]) # access arr[start:end:step]

[2 4 6] [2 4 6]


In [42]:
a[0:-1:1, 0:-1:2]

array([[1, 3, 5]])

In [45]:
a[1, 6] = 16
print(a)

a[:,3] = [5,6]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10  5 12 15 16]]
[[ 1  2  3  5  5  6  7]
 [ 8  9 10  6 12 15 16]]


## 3 d array example

In [46]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [48]:
print(f"dimension of array a: {a.ndim}")
print(f"shape of array a: {a.shape}")

dimension of array a: 3
shape of array a: (2, 2, 2)


In [49]:
print(a[0, 1, 1]) # access 4

4


In [50]:
a[:, 1, :]

array([[3, 4],
       [7, 8]])

In [51]:
a[:, 1, :] = [[9, 9], [8, 8]]
print(a)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initializing different types of arrays

In [53]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [55]:
np.zeros((6, 4), dtype="int32")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [56]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
a = np.full((3, 4), 12)
print(a)

[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]


In [60]:
np.full_like(a, -3, dtype="float64")

array([[-3., -3., -3., -3.],
       [-3., -3., -3., -3.],
       [-3., -3., -3., -3.]])

In [63]:
np.random.rand(3) # chooses random number between 0 and 1 for array size of 3

array([0.77788847, 0.32430769, 0.65898788])

In [64]:
np.random.rand(3, 4)

array([[0.87455048, 0.79509637, 0.43780248, 0.18952684],
       [0.63997694, 0.69360978, 0.72930485, 0.26499332],
       [0.30148726, 0.23784204, 0.95270607, 0.80589141]])

In [66]:
np.random.randint(-4, 5, (3, 4), dtype="int32")

array([[-3,  3,  1,  3],
       [ 1, -1,  1, -3],
       [ 2,  1,  4, -3]], dtype=int32)

In [69]:
arr = np.array([[1, 2, 3]])
n1 = np.repeat(arr, 4, axis=0)
print(n1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [70]:
n1 = np.repeat(arr, 4, axis=1)
print(n1)

[[1 1 1 1 2 2 2 2 3 3 3 3]]


## Excercise - initialize np array

**Specifications**
* create 5 * 5 array
* make all edges values to 1
* make center cell to 9
* make all remaining cell to 0

In [78]:
# Solution 1
res_arr = np.ones((5, 5), dtype="int16")

res_arr[1, 1:-1] = 0
res_arr[-2, 1:-1] = 0
res_arr[1:-1, 1] = 0
res_arr[1:-1, -2] = 0
res_arr[2, 2] = 9

print(res_arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [79]:
# Solution 2
res_arr = np.ones((5, 5), dtype="int16")

zero_arr = np.zeros((3, 3), dtype="int16")
zero_arr[1, 1] = 9

res_arr[1:-1, 1:-1] = zero_arr

print(res_arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Caution: copy operation

The assignment operator (=) right to left will pass the reference and should be avoided when we need copy of an object. Use copy method to have copy.

In [86]:
# referecing
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
# both arr1 and aar2 points to same reference by doing the below assignment
arr2 = arr1
arr2[-1] = 10
print(arr1, arr2)

[ 1  2  3  4  5  6 10] [ 1  2  3  4  5  6 10]


In [87]:
# copy object
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr2 = arr1.copy()
arr2[-1] = 10
print(arr1, arr2)

[1 2 3 4 5 6 7] [ 1  2  3  4  5  6 10]


## Mathematics - Operations
NumPy supports mathematics oprations and uses **broadcasting** tecnique to does it

In [88]:
a = np.array([1, 2, 3, 4, 5])

In [92]:
print(f"a + 2: {a + 2}")
print(f"a - 2: {a - 2}")
print(f"a * 2: {a * 2}")
print(f"a / 2: {a / 2}")
print(f"a // 2: {a // 2}")
print(f"a power 2: {a ** 2}")
print(f"sin(a): {np.sin(a)}")
print(f"cos(a): {np.cos(a)}")

a + 2: [3 4 5 6 7]
a - 2: [-1  0  1  2  3]
a * 2: [ 2  4  6  8 10]
a / 2: [0.5 1.  1.5 2.  2.5]
a // 2: [0 1 1 2 2]
a power 2: [ 1  4  9 16 25]
sin(a): [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
cos(a): [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [93]:
b = np.array([1, 2, 3, 4, 5, 6, 7])

In [94]:
print(f"a + b:\n {a + b}")

ValueError: operands could not be broadcast together with shapes (5,) (7,) 

In [95]:
b = np.array([1, 2, 3, 4, 5])

In [96]:
print(f"a + b: {a + b}")
print(f"a - b: {a - b}")
print(f"a * b: {a * b}")
print(f"a / b: {a / b}")
print(f"a // b: {a // b}")
print(f"a power b: {a ** b}")

a + b: [ 2  4  6  8 10]
a - b: [0 0 0 0 0]
a * b: [ 1  4  9 16 25]
a / b: [1. 1. 1. 1. 1.]
a // b: [1 1 1 1 1]
a power b: [   1    4   27  256 3125]


## Linear Algebra

In [104]:
# Matrix multiplication
arr1 = np.array([[2, 3, 4],
                 [5, 6, 7]])
arr2 = np.full((3, 4), 1, dtype="int32")
# matrix mulpication ((2*3) * (3*4) => (2*4)) (r1*c1) * (r2*c2) => (r1*c2)
print(np.matmul(arr1, arr2)) 

[[ 9  9  9  9]
 [18 18 18 18]]


In [105]:
# Identity of a matrix
print(np.linalg.det(np.ones((3, 3))))
print(np.linalg.det(np.identity((3))))

0.0
1.0


## Statistics

In [106]:
arr1 = np.array([[2, 3, 4],
                 [5, 6, 7]])

In [108]:
print(np.min(arr1, axis=1))

[2 5]


In [109]:
print(np.max(arr1, axis=0))

[5 6 7]


In [110]:
print(np.sum(arr1, axis=0), np.sum(arr1, axis=1))

[ 7  9 11] [ 9 18]


## Reorganizing

### Reshape

In [5]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"Before matrix:\n{before}")
print(f"After matrix 1 * 8:\n{before.reshape(1, 8)}")
print(f"After matrix 8 * 1:\n{before.reshape(8, 1)}")
print(f"After matrix 2 * 4:\n{before.reshape(2, 4)}")
print(f"After matrix 4 * 2:\n{before.reshape(4, 2)}")

Before matrix:
[[1 2 3 4]
 [5 6 7 8]]
After matrix 1 * 8:
[[1 2 3 4 5 6 7 8]]
After matrix 8 * 1:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
After matrix 2 * 4:
[[1 2 3 4]
 [5 6 7 8]]
After matrix 4 * 2:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Vertical stack

In [11]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr1 = np.array([1, 2, 3, 4])
print(np.vstack((arr1, before, arr1, before)))

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]


### Horizontal Stack

In [12]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr1 = np.array([[1, 2,], [3, 4]])
print(np.hstack((arr1, before, arr1, before)))

[[1 2 1 2 3 4 1 2 1 2 3 4]
 [3 4 5 6 7 8 3 4 5 6 7 8]]


## Miscellaneous

### Load data from txt file

In [14]:
filedata = np.genfromtxt('numbers.txt', delimiter=',')
print(filedata)
filedata_int = filedata.astype('int32')
print(filedata_int)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


### Boolean Masking and Advanced Indexing

In [17]:
filedata < 25

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True, False, False, False, False, False,
        False]])

In [19]:
filedata[filedata < 20].astype('int32')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19], dtype=int32)

In [27]:
filedata[(filedata > 5) & (filedata < 25)].astype('int32')

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24], dtype=int32)

In [28]:
filedata[~(filedata > 5) & (filedata < 25)].astype('int32')

array([1, 2, 3, 4, 5], dtype=int32)

## Excercise - Initialize np array

**Specifications**
* create 6 * 5 matrix
* assign the matrix with values from 1 to 39 horizontally first
* Index the created array

In [36]:
res_arr = np.array([[1, 2, 3, 4, 5]])
res_arr = np.repeat(res_arr, 6, axis=0)
sum_arr = np.array([[0], [5], [10], [15], [20], [25]])
res_arr = res_arr + sum_arr
print(res_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [37]:
# index [[11, 12], [16, 17]]
print(res_arr[2:4, :2])

[[11 12]
 [16 17]]


In [41]:
# index 2, 8, 14, 20
print(res_arr[[0, 1, 2, 3], [1, 2, 3, 4]])
print(np.diag(res_arr, k=1))

[ 2  8 14 20]
[ 2  8 14 20]


In [43]:
# index 4, 5, 24, 25, 29, 30
print(res_arr[[0, -2, -1], -2:])

[[ 4  5]
 [24 25]
 [29 30]]
